### ISSUE TITLE
Figures not displaying in rendered presentation

### ISSUE THREAD

**Issue by the-Hull** [gavinsimpson/intro-vegan-webinar-july-2020#1]
Dear Dr Simpson,

thanks for hosting this webinar! 
After reviewing the slides via the link you provided, I noticed that figures are not displaying. 

They are currently pointing to e.g.:

> https://fromthebottomoftheheap.net/slides/intro-vegan-webinar-2020/intro-to-vegan_files/figure-html/diversity-5-1.svg 

with a 404.

All the best and looking forward to the session!

Alex

**Comment by gavinsimpson** [comment]
Thanks @the-Hull; I forgot to push `intro-to-vegan_files/` folder. Fixing now.
